// Copyright 2016 David Lavieri.  All rights reserved.
// Use of this source code is governed by a MIT License
// License that can be found in the LICENSE file.

export const TODO_FETCH_PENDING = 'TODO_FETCH_PENDING';
export const TODO_FETCH_FULFILLED = 'TODO_FETCH_FULFILLED';
export const TODO_FETCH_REJECTED = 'TODO_FETCH_REJECTED';

export const TODO_GET_PENDING = 'TODO_GET_PENDING';
export const TODO_GET_FULFILLED = 'TODO_GET_FULFILLED';
export const TODO_GET_REJECTED = 'TODO_GET_REJECTED';

export const TODO_ADD_PENDING = 'TODO_ADD_PENDING';
export const TODO_ADD_FULFILLED = 'TODO_ADD_FULFILLED';
export const TODO_ADD_REJECTED = 'TODO_ADD_REJECTED';

export const TODO_UPDATE_PENDING = 'TODO_UPDATE_PENDING';
export const TODO_UPDATE_FULFILLED = 'TODO_UPDATE_FULFILLED';
export const TODO_UPDATE_REJECTED = 'TODO_UPDATE_REJECTED';

export const TODO_DELETE_PENDING = 'TODO_DELETE_PENDING';
export const TODO_DELETE_FULFILLED = 'TODO_DELETE_FULFILLED';
export const TODO_DELETE_REJECTED = 'TODO_DELETE_REJECTED';

export const TODO_CHANGE_PAGE = 'TODO_CHANGE_PAGE';
export const TODO_CHANGE_PAGE_SIZE = 'TODO_CHANGE_PAGE_SIZE';
export const TODO_CHANGE_COMPLETED = 'TODO_CHANGE_COMPLETED';
export const TODO_RELOAD = 'TODO_RELOAD';
